apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-api
  namespace: rpa-system
  labels:
    app.kubernetes.io/name: rpa-api
    app.kubernetes.io/part-of: rpa-enterprise
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-worker
  namespace: rpa-system
  labels:
    app.kubernetes.io/name: rpa-worker
    app.kubernetes.io/part-of: rpa-enterprise
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-lifecycle-worker
  namespace: rpa-system
  labels:
    app.kubernetes.io/name: rpa-lifecycle-worker
    app.kubernetes.io/part-of: rpa-enterprise
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-console
  namespace: rpa-system
  labels:
    app.kubernetes.io/name: rpa-console
    app.kubernetes.io/part-of: rpa-enterprise
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-migrate
  namespace: rpa-system
  labels:
    app.kubernetes.io/name: rpa-migrate
    app.kubernetes.io/part-of: rpa-enterprise
automountServiceAccountToken: false
