apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-serviceaccounts.yaml
  - 02-configmap.yaml
  - 03-secret.example.yaml
  - 10-migrate-job.yaml
  - 20-api.yaml
  - 21-worker.yaml
  - 22-lifecycle-worker.yaml
  - 30-policies.yaml
  - 31-api-hpa.yaml
