import type { RbacAction, Role } from "./security-middleware-contract";

export const RBAC_ROLE_LABELS: Readonly<Record<Role, string>> = {
  viewer: "뷰어",
  operator: "운영자",
  reviewer: "검토자",
  approver: "승인자",
  admin: "관리자",
};

export const RBAC_ROLE_ACTIONS: Readonly<Record<Role, readonly RbacAction[]>> = {
  viewer: [
    "run.read",
    "workitem.read",
    "human_task.read",
    "principal.read",
    "artifact.read",
    "site.read",
    "gateway_policy.read",
    "scenario.read",
    "trigger.read",
    "ops_alert.read",
    "automation_idea.read",
    "connector.read",
    "document_job.read",
    "audit.read",
  ],
  operator: [
    "run.read",
    "run.create",
    "site.create",
    "site.update",
    "session.capture",
    "workitem.read",
    "human_task.read",
    "principal.read",
    "artifact.read",
    "site.read",
    "gateway_policy.read",
    "run.abort",
    "human_task.assign",
    "human_task.start",
    "dlq.replay",
    "sink_dlq.replay",
    "scenario.read",
    "scenario.create",
    "scenario.update",
    "trigger.read",
    "trigger.manage",
    "ops_alert.read",
    "automation_idea.read",
    "automation_idea.manage",
    "connector.read",
    "document_job.read",
    "document_job.manage",
    "audit.read",
  ],
  reviewer: [
    "run.read",
    "run.create",
    "site.create",
    "site.update",
    "session.capture",
    "workitem.read",
    "human_task.read",
    "principal.read",
    "artifact.read",
    "site.read",
    "gateway_policy.read",
    "run.abort",
    "human_task.assign",
    "human_task.escalate",
    "human_task.start",
    "dlq.replay",
    "sink_dlq.replay",
    "human_task.resolve.validation",
    "human_task.resolve.exception",
    "human_task.resolve.captcha",
    "human_task.resolve.mfa",
    "scenario.read",
    "scenario.create",
    "scenario.update",
    "trigger.read",
    "trigger.manage",
    "ops_alert.read",
    "automation_idea.read",
    "automation_idea.manage",
    "connector.read",
    "document_job.read",
    "document_job.manage",
    "audit.read",
  ],
  approver: [
    "run.read",
    "run.create",
    "site.create",
    "site.update",
    "session.capture",
    "workitem.read",
    "human_task.read",
    "principal.read",
    "artifact.read",
    "site.read",
    "gateway_policy.read",
    "run.abort",
    "human_task.assign",
    "human_task.escalate",
    "human_task.start",
    "dlq.replay",
    "sink_dlq.replay",
    "human_task.resolve.validation",
    "human_task.resolve.exception",
    "human_task.resolve.captcha",
    "human_task.resolve.mfa",
    "human_task.resolve.approval",
    "node_policy.approve",
    "site.approve",
    "approval.decide",
    "scenario.read",
    "scenario.create",
    "scenario.update",
    "scenario.promote.approve",
    "trigger.read",
    "trigger.manage",
    "ops_alert.read",
    "automation_idea.read",
    "automation_idea.manage",
    "automation_idea.approve",
    "connector.read",
    "document_job.read",
    "document_job.manage",
    "audit.read",
  ],
  admin: [
    "run.read",
    "run.create",
    "site.create",
    "site.update",
    "session.capture",
    "workitem.read",
    "human_task.read",
    "principal.read",
    "artifact.read",
    "site.read",
    "gateway_policy.read",
    "run.abort",
    "human_task.assign",
    "human_task.escalate",
    "human_task.start",
    "dlq.replay",
    "sink_dlq.replay",
    "human_task.resolve.validation",
    "human_task.resolve.exception",
    "human_task.resolve.captcha",
    "human_task.resolve.mfa",
    "human_task.resolve.approval",
    "node_policy.approve",
    "site.approve",
    "approval.decide",
    "secret.resolve",
    "credential.manage",
    "worker_pool.manage",
    "connector.enable",
    "gateway_policy.edit",
    "network_policy.edit",
    "principal.manage",
    "rbac.grant",
    "scenario.read",
    "scenario.create",
    "scenario.update",
    "scenario.promote",
    "scenario.promote.approve",
    "trigger.read",
    "trigger.manage",
    "ops_alert.read",
    "automation_idea.read",
    "automation_idea.manage",
    "automation_idea.approve",
    "connector.read",
    "document_job.read",
    "document_job.manage",
    "audit.read",
  ],
};

export const ALL_RBAC_ACTIONS = [
  "run.read",
  "run.create",
  "run.abort",
  "trigger.read",
  "trigger.manage",
  "ops_alert.read",
  "automation_idea.read",
  "automation_idea.manage",
  "automation_idea.approve",
  "document_job.read",
  "document_job.manage",
  "audit.read",
  "workitem.read",
  "human_task.read",
  "principal.read",
  "human_task.assign",
  "human_task.escalate",
  "human_task.start",
  "human_task.resolve.validation",
  "human_task.resolve.exception",
  "human_task.resolve.captcha",
  "human_task.resolve.mfa",
  "human_task.resolve.approval",
  "node_policy.approve",
  "dlq.replay",
  "sink_dlq.replay",
  "scenario.create",
  "scenario.read",
  "scenario.update",
  "scenario.promote",
  "scenario.promote.approve",
  "artifact.read",
  "site.read",
  "site.approve",
  "site.create",
  "site.update",
  "approval.decide",
  "session.capture",
  "secret.resolve",
  "credential.manage",
  "worker_pool.manage",
  "connector.read",
  "connector.enable",
  "gateway_policy.read",
  "gateway_policy.edit",
  "network_policy.edit",
  "principal.manage",
  "rbac.grant",
] as const satisfies readonly RbacAction[];

function invertRoleActions(): Readonly<Record<RbacAction, readonly Role[]>> {
  const out = Object.fromEntries(ALL_RBAC_ACTIONS.map((action) => [action, [] as Role[]])) as Record<RbacAction, Role[]>;
  for (const role of Object.keys(RBAC_ROLE_ACTIONS) as Role[]) {
    for (const action of RBAC_ROLE_ACTIONS[role]) {
      out[action].push(role);
    }
  }
  return out;
}

export const RBAC_ALLOWED_ROLES = invertRoleActions();

export function roleAllowsAction(role: Role, action: RbacAction): boolean {
  return RBAC_ROLE_ACTIONS[role].includes(action);
}

export function rolesAllowAction(roles: readonly Role[], action: RbacAction): boolean {
  return roles.some((role) => roleAllowsAction(role, action));
}
