apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rpa-api
  namespace: {{ include "rpa.namespace" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rpa-api
      app.kubernetes.io/component: api
