apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-api
  namespace: {{ include "rpa.namespace" . }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-worker
  namespace: {{ include "rpa.namespace" . }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-lifecycle-worker
  namespace: {{ include "rpa.namespace" . }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-console
  namespace: {{ include "rpa.namespace" . }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpa-migrate
  namespace: {{ include "rpa.namespace" . }}
automountServiceAccountToken: false
