// automation-performance-report.ts 에서 추출 — CSV 내보내기 빌더(동작 무변경 이동, 헤더/포맷 verbatim).
import { csvCell } from "./csv";
import {
  listCell,
  roiSampleIdeasCell,
  roiSourceCountsCell,
  roiStageCountsCell,
} from "./automation-performance-report-export-cells";
import type { AutomationPerformanceReport } from "./automation-performance-report-types";

export function reportToCsv(report: AutomationPerformanceReport): string {
  const summaryLines = [
    ["metric", "value"],
    ["month", report.month],
    ["run_mode", report.run_mode],
    ["timezone", report.timezone],
    ["period_start", report.period_start],
    ["period_end", report.period_end],
    ["total_runs", String(report.summary.total_runs)],
    ["completed", String(report.summary.completed)],
    ["failed_business", String(report.summary.failed_business)],
    ["failed_system", String(report.summary.failed_system)],
    ["success_rate", rateCell(report.summary.success_rate)],
    ["rerun_count", String(report.summary.rerun_count)],
    ["reprocessing_rate", rateCell(report.summary.reprocessing_rate)],
    ["estimated_hours_saved", String(report.summary.estimated_hours_saved)],
    ["estimated_value", String(report.summary.estimated_value)],
    ["implementation_effort", String(report.summary.implementation_effort)],
    ["net_value", String(report.summary.net_value)],
    ["value_to_cost_ratio", rateCell(report.summary.value_to_cost_ratio)],
    ["payback_months", rateCell(report.summary.payback_months)],
    ["gateway_cost", String(report.summary.gateway_cost)],
    ["completed_cost", String(report.summary.cost_by_status.completed)],
    ["failed_business_cost", String(report.summary.cost_by_status.failed_business)],
    ["failed_system_cost", String(report.summary.cost_by_status.failed_system)],
    ["failed_cost", String(report.summary.failed_cost)],
    ["other_cost", String(report.summary.cost_by_status.other)],
    ["rerun_cost", String(report.summary.rerun_cost)],
    ["avg_cost_per_run", rateCell(report.summary.avg_cost_per_run)],
    ["cost_per_completed_run", rateCell(report.summary.cost_per_completed_run)],
    ["llm_call_cost", rateCell(report.summary.llm_call_cost)],
    ["run_vs_call_cost_delta", rateCell(report.summary.run_vs_call_cost_delta)],
    ["roi_idea_count", String(report.summary.roi_idea_count)],
    ["roi_confidence_low", String(report.summary.roi_confidence.low)],
    ["roi_confidence_medium", String(report.summary.roi_confidence.medium)],
    ["roi_confidence_high", String(report.summary.roi_confidence.high)],
    ["roi_source_counts", roiSourceCountsCell(report.summary.roi_source_lineage)],
    ["roi_stage_counts", roiStageCountsCell(report.summary.roi_source_lineage)],
    ["roi_departments", listCell(report.summary.roi_source_lineage.departments)],
    ["roi_business_owners", listCell(report.summary.roi_source_lineage.business_owners)],
    ["roi_sample_ideas", roiSampleIdeasCell(report.summary.roi_source_lineage)],
    ["roi_actual_evidence_count", String(report.summary.roi_actuals.evidence_count)],
    ["estimated_transaction_count", String(report.summary.roi_actuals.estimated_transaction_count)],
    ["actual_transaction_count", String(report.summary.roi_actuals.actual_transaction_count)],
    ["comparable_actual_transaction_count", String(report.summary.roi_actuals.comparable_actual_transaction_count)],
    ["transaction_attainment_rate", rateCell(report.summary.roi_actuals.transaction_attainment_rate)],
    ["estimated_exception_rate", rateCell(report.summary.roi_actuals.estimated_exception_rate)],
    ["actual_failure_rate", rateCell(report.summary.roi_actuals.actual_failure_rate)],
    ["comparable_actual_failure_rate", rateCell(report.summary.roi_actuals.comparable_actual_failure_rate)],
    ["failure_rate_delta", rateCell(report.summary.roi_actuals.failure_rate_delta)],
    ["human_intervention_minutes", String(report.summary.roi_actuals.human_intervention_minutes)],
    ["actual_reprocessing_minutes", String(report.summary.roi_actuals.reprocessing_minutes)],
    ["latest_roi_actual_period_end", report.summary.roi_actuals.latest_period_end ?? ""],
    ["decision_signal_status", report.summary.decision_signal.status],
    ["decision_signal_reason", report.summary.decision_signal.reason],
  ];
  const failureLines = [["code", "count"], ...report.failure_top.map((row) => [row.code, String(row.count)])];
  const modelCostLines = [
    ["model", "calls", "input_tokens", "output_tokens", "cost", "cost_share"],
    ...report.cost_by_model.map((row) => [
      row.model,
      String(row.calls),
      nullableNumberCell(row.input_tokens),
      nullableNumberCell(row.output_tokens),
      nullableNumberCell(row.cost),
      rateCell(row.cost_share),
    ]),
  ];
  const modelCostTrendLines = [
    ["day", "model", "calls", "input_tokens", "output_tokens", "cost", "cost_share_of_day", "cost_delta_from_previous_day_for_model"],
    ...report.model_cost_trends.map((row) => [
      row.day,
      row.model,
      String(row.calls),
      nullableNumberCell(row.input_tokens),
      nullableNumberCell(row.output_tokens),
      nullableNumberCell(row.cost),
      rateCell(row.cost_share_of_day),
      rateCell(row.cost_delta_from_previous_day_for_model),
    ]),
  ];
  const trendLines = [
    [
      "day",
      "total_runs",
      "completed",
      "failed_business",
      "failed_system",
      "success_rate",
      "rerun_count",
      "reprocessing_rate",
      "gateway_cost",
      "completed_cost",
      "failed_business_cost",
      "failed_system_cost",
      "other_cost",
      "rerun_cost",
      "avg_cost_per_run",
      "cost_per_completed_run",
      "cost_delta_from_previous_day",
    ],
    ...report.trends.map((row) => [
      row.day,
      String(row.total_runs),
      String(row.completed),
      String(row.failed_business),
      String(row.failed_system),
      rateCell(row.success_rate),
      String(row.rerun_count),
      rateCell(row.reprocessing_rate),
      String(row.gateway_cost),
      String(row.cost_by_status.completed),
      String(row.cost_by_status.failed_business),
      String(row.cost_by_status.failed_system),
      String(row.cost_by_status.other),
      String(row.rerun_cost),
      rateCell(row.avg_cost_per_run),
      rateCell(row.cost_per_completed_run),
      rateCell(row.cost_delta_from_previous_day),
    ]),
  ];
  const workflowLines = [
    [
      "scenario_id",
      "scenario_name",
      "total_runs",
      "completed",
      "failed_business",
      "failed_system",
      "success_rate",
      "rerun_count",
      "reprocessing_rate",
      "estimated_hours_saved",
      "estimated_value",
      "implementation_effort",
      "net_value",
      "value_to_cost_ratio",
      "payback_months",
      "gateway_cost",
      "completed_cost",
      "failed_business_cost",
      "failed_system_cost",
      "other_cost",
      "rerun_cost",
      "avg_cost_per_run",
      "cost_per_completed_run",
      "roi_idea_count",
      "roi_confidence_low",
      "roi_confidence_medium",
      "roi_confidence_high",
      "roi_source_counts",
      "roi_stage_counts",
      "roi_departments",
      "roi_business_owners",
      "roi_sample_ideas",
      "roi_actual_evidence_count",
      "estimated_transaction_count",
      "actual_transaction_count",
      "comparable_actual_transaction_count",
      "transaction_attainment_rate",
      "estimated_exception_rate",
      "actual_failure_rate",
      "comparable_actual_failure_rate",
      "failure_rate_delta",
      "human_intervention_minutes",
      "actual_reprocessing_minutes",
      "latest_roi_actual_period_end",
      "decision_signal_status",
      "decision_signal_reason",
    ],
    ...report.by_workflow.map((row) => [
      row.scenario_id,
      row.scenario_name,
      String(row.total_runs),
      String(row.completed),
      String(row.failed_business),
      String(row.failed_system),
      rateCell(row.success_rate),
      String(row.rerun_count),
      rateCell(row.reprocessing_rate),
      String(row.estimated_hours_saved),
      String(row.estimated_value),
      String(row.implementation_effort),
      String(row.net_value),
      rateCell(row.value_to_cost_ratio),
      rateCell(row.payback_months),
      String(row.gateway_cost),
      String(row.cost_by_status.completed),
      String(row.cost_by_status.failed_business),
      String(row.cost_by_status.failed_system),
      String(row.cost_by_status.other),
      String(row.rerun_cost),
      rateCell(row.avg_cost_per_run),
      rateCell(row.cost_per_completed_run),
      String(row.roi_idea_count),
      String(row.roi_confidence.low),
      String(row.roi_confidence.medium),
      String(row.roi_confidence.high),
      roiSourceCountsCell(row.roi_source_lineage),
      roiStageCountsCell(row.roi_source_lineage),
      listCell(row.roi_source_lineage.departments),
      listCell(row.roi_source_lineage.business_owners),
      roiSampleIdeasCell(row.roi_source_lineage),
      String(row.roi_actuals.evidence_count),
      String(row.roi_actuals.estimated_transaction_count),
      String(row.roi_actuals.actual_transaction_count),
      String(row.roi_actuals.comparable_actual_transaction_count),
      rateCell(row.roi_actuals.transaction_attainment_rate),
      rateCell(row.roi_actuals.estimated_exception_rate),
      rateCell(row.roi_actuals.actual_failure_rate),
      rateCell(row.roi_actuals.comparable_actual_failure_rate),
      rateCell(row.roi_actuals.failure_rate_delta),
      String(row.roi_actuals.human_intervention_minutes),
      String(row.roi_actuals.reprocessing_minutes),
      row.roi_actuals.latest_period_end ?? "",
      row.decision_signal.status,
      row.decision_signal.reason,
    ]),
  ];
  return [
    ["Summary"],
    ...summaryLines,
    [],
    ["Failure Top N"],
    ...failureLines,
    [],
    ["Cost By Model"],
    ...modelCostLines,
    [],
    ["Model Cost Trends"],
    ...modelCostTrendLines,
    [],
    ["Daily Trends"],
    ...trendLines,
    [],
    ["Workflow ROI"],
    ...workflowLines,
  ]
    .map((line) => line.map(csvCell).join(","))
    .join("\n");
}

function rateCell(value: number | null): string {
  return value === null ? "" : String(value);
}

function nullableNumberCell(value: number | null): string {
  return value === null ? "" : String(value);
}
