export type ConnectorKind = "browser" | "api" | "file" | "notification" | "data";
export type CatalogStatus = "available" | "candidate" | "requires_admin" | "blocked";

export interface ConnectorCatalogItem {
  catalog_id: string;
  connector_id: string;
  name: string;
  kind: ConnectorKind;
  category: string;
  status: CatalogStatus;
  priority: "P0" | "P1" | "P2" | "P3";
  summary: string;
  best_for: readonly string[];
  supported_actions: readonly string[];
  template_ids: readonly string[];
  required_rbac_actions: readonly string[];
  required_secret_refs: readonly string[];
  allowed_domains: readonly string[];
  manifest_permissions: {
    api: readonly ("migrateSchema" | "registerTargets" | "readConfig")[];
    network: false;
    secret_refs: readonly string[];
  };
  implementation_state: string;
  security_notes: readonly string[];
  created_at: string;
  updated_at: string;
}

export const CONNECTORS: readonly ConnectorCatalogItem[] = [
  {
    catalog_id: "91000000-0000-4000-8000-000000000001",
    connector_id: "sap-web",
    name: "SAP 웹 / ERP 포털",
    kind: "browser",
    category: "ERP",
    status: "candidate",
    priority: "P0",
    summary: "목록 추출·결재·증빙 캡처를 위한 브라우저 우선 SAP·ERP 포털 자동화 템플릿.",
    best_for: ["주문 조회", "송장 상태", "결재 포털", "기준정보 조회"],
    supported_actions: ["navigate", "act", "extract", "verify", "human_task"],
    template_ids: ["sap-web-list-extract", "sap-web-approval-check"],
    required_rbac_actions: ["connector.read", "site.read", "scenario.create"],
    required_secret_refs: ["secret://<env>/connector/sap-web/*"],
    allowed_domains: ["*.sap.example.com", "*.erp.example.com"],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: ["secret://<env>/connector/sap-web/*"] },
    implementation_state: "browser template pack for approved web portals",
    security_notes: ["자격증명 값은 보안 자격증명 저장소 안에만 보관됩니다.", "고위험 사이트 실행은 여전히 사이트 승인이 필요합니다."],
    created_at: "2026-06-23T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000002",
    connector_id: "http-api",
    name: "HTTP API",
    kind: "api",
    category: "Integration",
    status: "requires_admin",
    priority: "P0",
    summary: "보안 베어러 자격증명을 사용하는 브라우저 RPA 업무용, 승인된 HTTP 연동 템플릿 메타데이터.",
    best_for: ["시스템 간 조회", "상태 업데이트", "웹훅 발송"],
    supported_actions: ["api_call", "verify"],
    template_ids: ["http-api-status-check"],
    required_rbac_actions: ["connector.read", "connector.enable"],
    required_secret_refs: ["secret://<env>/connector/http-api/*"],
    allowed_domains: ["api.example.com"],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: ["secret://<env>/connector/http-api/*"] },
    implementation_state: "HTTP API P1 supports approved bearer-token profiles; basic auth, mTLS, and OAuth profiles require a future connector profile contract",
    security_notes: ["인증 헤더(Authorization)는 템플릿 본문에 저장하지 않습니다.", "베어러 토큰은 보안 자격증명 경계 안에서만 해소됩니다.", "활성화·설치 시 커넥터 보안 감사 결정을 반드시 남깁니다."],
    created_at: "2026-06-22T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000007",
    connector_id: "managed-idp-scim",
    name: "관리형 IdP SCIM",
    kind: "api",
    category: "Identity",
    status: "requires_admin",
    priority: "P0",
    summary: "관리형 IdP SCIM 제공자 등록·그룹-역할 가져오기·폐기 증빙을 위한 메타데이터 전용 설정 템플릿.",
    best_for: ["SCIM 제공자 온보딩", "IdP 그룹-역할 정합", "제공자 폐기 증빙"],
    supported_actions: ["scim_provider_register", "scim_group_role_import", "scim_provider_decommission"],
    template_ids: ["managed-idp-scim-provider-registration", "managed-idp-scim-group-role-import", "managed-idp-scim-provider-decommission"],
    required_rbac_actions: ["connector.read", "scim.sync"],
    required_secret_refs: ["secret://<tenant>/scim/<provider_key>/signing"],
    allowed_domains: [],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: ["secret://<tenant>/scim/<provider_key>/signing"] },
    implementation_state: "SCIM P1 uses /v1/scim/providers, group-role mapping import, and signed inbound scim-principal@1; no outbound IdP network connector is required.",
    security_notes: [
      "제공자 서명 자료는 보안 저장소 안에만 보관되며 signature_secret_ref 로만 참조합니다.",
      "인바운드 SCIM 동기화는 connectorId=scim:<provider_key> 를 통해 서명 보안 연결을 해소합니다.",
      "외부 그룹 의미는 추론하지 않으며, 저장소가 소유한 그룹-역할 매핑 행만 신뢰합니다.",
    ],
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000008",
    connector_id: "existing-rpa-handoff",
    name: "기존 RPA 핸드오프 프로필",
    kind: "api",
    category: "Federation",
    status: "requires_admin",
    priority: "P1",
    summary: "UiPath·Automation Anywhere·Power Automate·Blue Prism 핸드오프 원장을 위한 메타데이터 전용 제공자 프로필입니다. 벤더 API/OAuth 직접 커넥터가 아닙니다.",
    best_for: ["외부 RPA 작업 핸드오프", "제공자 접수 증빙 캡처", "공존 마이그레이션", "데스크톱 자동화 연합"],
    supported_actions: ["handoff_request", "dispatch_attempt", "receipt_record", "provider_callback"],
    template_ids: [
      "uipath-handoff-provider-profile",
      "automation-anywhere-handoff-provider-profile",
      "power-automate-handoff-provider-profile",
      "blue-prism-handoff-provider-profile",
    ],
    required_rbac_actions: ["connector.read", "integration.handoff"],
    required_secret_refs: ["secret://<tenant>/integration/<provider_alias>/callback-url", "secret://<tenant>/integration/<provider_alias>/callback-signing", "secret://<tenant>/integration/<provider_alias>/dispatch-endpoint"],
    allowed_domains: [],
    manifest_permissions: {
      api: ["readConfig"],
      network: false,
      secret_refs: ["secret://<tenant>/integration/<provider_alias>/callback-url", "secret://<tenant>/integration/<provider_alias>/callback-signing", "secret://<tenant>/integration/<provider_alias>/dispatch-endpoint"],
    },
    implementation_state: "P1 metadata-only integration handoff ledger, dispatch attempt ledger, SecretRef-backed dispatch, and provider receipt/callback capture are implemented; vendor API/OAuth, queue mapping, and endpoint ownership remain owner/provider decisions.",
    security_notes: [
      "카탈로그는 제공자 별칭과 보안 연결 네임스페이스만 노출하며, 벤더 실제 엔드포인트·OAuth 클라이언트·토큰·해소된 보안 연결 값은 노출하지 않습니다.",
      "생성은 부작용이 없으며, ‘접수됨’은 제공자 접수(2xx)를 의미할 뿐 업무 완료가 아닙니다.",
      "벤더별 API·OAuth 동작은 테넌트가 프로필을 활성화하기 전에 오너/제공자의 승인을 받아야 합니다.",
    ],
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000003",
    connector_id: "excel-csv",
    name: "Excel / CSV 브라우저 파일",
    kind: "file",
    category: "Office",
    status: "candidate",
    priority: "P1",
    summary: "CSV·스프레드시트형 내보내기를 위한 브라우저 다운로드/업로드 파일 업무 템플릿.",
    best_for: ["리포트 다운로드", "대량 업로드", "대사 파일"],
    supported_actions: ["navigate", "act", "extract", "artifact"],
    template_ids: ["browser-report-download"],
    required_rbac_actions: ["connector.read", "artifact.read", "scenario.create"],
    required_secret_refs: [],
    allowed_domains: ["reports.example.com"],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: [] },
    implementation_state: "browser artifact workflow for report download and upload",
    security_notes: ["다운로드한 증빙은 마스킹·권한(RBAC) 게이트 뒤에 보관됩니다."],
    created_at: "2026-06-21T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000006",
    connector_id: "document-idp",
    name: "문서 IDP (브라우저 증빙)",
    kind: "file",
    category: "Document Automation",
    status: "candidate",
    priority: "P1",
    summary: "마스킹 적용된 브라우저 증빙을 위한 내장 결정형 문서 추출·검증 템플릿.",
    best_for: ["송장 검토", "계약 항목 확인", "브라우저 다운로드 증빙", "검증 대기열"],
    supported_actions: ["artifact", "extract", "human_task", "verify"],
    template_ids: ["document-idp-validation"],
    required_rbac_actions: ["connector.read", "artifact.read", "human_task.read", "scenario.create"],
    required_secret_refs: [],
    allowed_domains: ["reports.example.com", "vendor.example.com"],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: [] },
    implementation_state: "P1 engine: built_in_deterministic_text_v1 over redaction-visible text/CSV/JSON artifacts; OCR and image decoding require a future document adapter",
    security_notes: [
      "문서 원문(바이트)은 P1 에서 테넌트 경계 안에 머뭅니다.",
      "증빙 본문 접근은 기존 증빙 마스킹·권한(RBAC)·감사 게이트를 그대로 거칩니다.",
      "이미지 OCR/PDF 디코딩은 향후 문서 어댑터 계약에서 다룹니다.",
    ],
    created_at: "2026-06-23T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000004",
    connector_id: "ops-webhook-sender",
    name: "운영 알림 웹훅 발송기",
    kind: "notification",
    category: "Notification",
    status: "available",
    priority: "P1",
    summary: "운영 알림용으로 구현된 보안 연결 기반 범용 HTTPS 웹훅 발송기. 발송 시도와 제공자 접수/회신을 메타데이터만으로 원장에 기록합니다.",
    best_for: ["실패 알림 웹훅", "사람 확인 에스컬레이션 웹훅", "SLA 위험 알림"],
    supported_actions: ["notify", "receipt_record", "provider_callback"],
    template_ids: ["ops-failure-alert"],
    required_rbac_actions: ["connector.read", "ops_alert.deliver"],
    required_secret_refs: ["secret://<tenant>/notification-sender/webhook/<route_alias>/endpoint"],
    allowed_domains: [],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: ["secret://<tenant>/notification-sender/webhook/<route_alias>/endpoint"] },
    implementation_state: "Implemented: /v1/ops-alerts/{alert_id}/deliveries/send-webhook queues durable SecretRef-backed webhook attempts; /v1/ops-alerts/{alert_id}/deliveries and /v1/webhooks/ops-alerts/{tenant_id}/{attempt_id} record metadata-only receipts/callbacks.",
    security_notes: [
      "웹훅 URL 은 비밀 값이며 보안 연결로만 관리합니다. 엔드포인트 URL·토큰·인증 헤더·제공자 응답 본문·해소된 보안 연결 값은 카탈로그 데이터가 아닙니다.",
      "HTTP 2xx 웹훅 응답은 ‘발송됨’ 증빙이지 ‘전달됨’ 증빙이 아닙니다.",
      "Teams/Slack/이메일/PagerDuty/ServiceNow 별 인증·수신자 해소·전달 접수 의미는 오너/제공자 결정 사항입니다.",
    ],
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000009",
    connector_id: "slack-notification-candidate",
    name: "Slack 알림 프로필 후보",
    kind: "notification",
    category: "Notification",
    status: "candidate",
    priority: "P2",
    summary: "Slack 전용 알림 프로필 후보입니다. 범용 웹훅 발송은 보안 연결 엔드포인트로 보낼 수 있지만, Slack 앱/OAuth/인증·채널 소유·전달 접수는 오너/제공자 증빙이 필요합니다.",
    best_for: ["Slack 운영 채널 검토", "오너 승인 Slack 알림 경로"],
    supported_actions: ["owner_evidence_review"],
    template_ids: [],
    required_rbac_actions: ["connector.read"],
    required_secret_refs: [],
    allowed_domains: [],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: [] },
    implementation_state: "candidate: owner/provider evidence required before Slack-specific auth mode, route ownership, recipient/channel resolution, or delivery receipt semantics can be approved",
    security_notes: ["Slack 웹훅 URL·봇 토큰·앱 시크릿·채널 명단·해소된 보안 연결 값을 카탈로그에 저장하지 마세요."],
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000010",
    connector_id: "teams-notification-candidate",
    name: "Teams 알림 프로필 후보",
    kind: "notification",
    category: "Notification",
    status: "candidate",
    priority: "P2",
    summary: "Microsoft Teams 전용 알림 프로필 후보입니다. 범용 웹훅 발송은 보안 연결 엔드포인트로 보낼 수 있지만, Teams 앱/인증·채널 소유·전달 접수는 오너/제공자 증빙이 필요합니다.",
    best_for: ["Teams 운영 채널 검토", "오너 승인 Teams 알림 경로"],
    supported_actions: ["owner_evidence_review"],
    template_ids: [],
    required_rbac_actions: ["connector.read"],
    required_secret_refs: [],
    allowed_domains: [],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: [] },
    implementation_state: "candidate: owner/provider evidence required before Teams-specific auth mode, route ownership, recipient/channel resolution, or delivery receipt semantics can be approved",
    security_notes: ["Teams 웹훅 URL·앱 시크릿·채널 명단·해소된 보안 연결 값을 카탈로그에 저장하지 마세요."],
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000011",
    connector_id: "email-notification-candidate",
    name: "이메일 알림 프로필 후보",
    kind: "notification",
    category: "Notification",
    status: "candidate",
    priority: "P2",
    summary: "이메일 전용 알림 프로필 후보입니다. SMTP/OAuth/인증·수신 그룹 확장·전달/반송 접수는 오너/제공자 증빙이 필요합니다.",
    best_for: ["이메일 에스컬레이션 검토", "오너 승인 메일 경로"],
    supported_actions: ["owner_evidence_review"],
    template_ids: [],
    required_rbac_actions: ["connector.read"],
    required_secret_refs: [],
    allowed_domains: [],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: [] },
    implementation_state: "candidate: owner/provider evidence required before email provider auth, recipient-group resolution, bounce handling, or delivery receipt semantics can be approved",
    security_notes: ["SMTP 비밀번호·OAuth 클라이언트/시크릿·수신자 명단 원본·메시지 본문·해소된 보안 연결 값을 카탈로그에 저장하지 마세요."],
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000012",
    connector_id: "pagerduty-notification-candidate",
    name: "PagerDuty 인시던트 프로필 후보",
    kind: "notification",
    category: "Notification",
    status: "candidate",
    priority: "P2",
    summary: "PagerDuty 전용 인시던트 프로필 후보입니다. 인시던트 라우팅 키·에스컬레이션 정책 소유·접수/해결 접수 의미는 오너/제공자 증빙이 필요합니다.",
    best_for: ["인시던트 에스컬레이션 검토", "오너 승인 PagerDuty 경로"],
    supported_actions: ["owner_evidence_review"],
    template_ids: [],
    required_rbac_actions: ["connector.read"],
    required_secret_refs: [],
    allowed_domains: [],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: [] },
    implementation_state: "candidate: owner/provider evidence required before PagerDuty-specific auth, escalation policy mapping, incident ownership, or incident receipt semantics can be approved",
    security_notes: ["PagerDuty 라우팅 키·토큰·에스컬레이션 명단·인시던트 본문·해소된 보안 연결 값을 카탈로그에 저장하지 마세요."],
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000013",
    connector_id: "servicenow-notification-candidate",
    name: "ServiceNow 인시던트 프로필 후보",
    kind: "notification",
    category: "Notification",
    status: "candidate",
    priority: "P2",
    summary: "ServiceNow 전용 인시던트 프로필 후보입니다. 인스턴스 소유·인증·인시던트 필드 매핑·접수/해결 접수 의미는 오너/제공자 증빙이 필요합니다.",
    best_for: ["ITSM 인시던트 검토", "오너 승인 ServiceNow 경로"],
    supported_actions: ["owner_evidence_review"],
    template_ids: [],
    required_rbac_actions: ["connector.read"],
    required_secret_refs: [],
    allowed_domains: [],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: [] },
    implementation_state: "candidate: owner/provider evidence required before ServiceNow-specific auth, table/field mapping, assignment routing, or incident receipt semantics can be approved",
    security_notes: ["ServiceNow 아이디/비밀번호·OAuth 시크릿·인시던트 본문 원본·배정 명단·해소된 보안 연결 값을 카탈로그에 저장하지 마세요."],
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "91000000-0000-4000-8000-000000000005",
    connector_id: "database-read",
    name: "데이터베이스 조회",
    kind: "data",
    category: "Data",
    status: "blocked",
    priority: "P2",
    summary: "기획용 데이터베이스 조회 커넥터 후보입니다. 브라우저 범위 예외 승인 후에만 활성화합니다.",
    best_for: ["참조 조회", "대사", "감사 증빙 결합"],
    supported_actions: ["query"],
    template_ids: [],
    required_rbac_actions: ["connector.read", "connector.enable"],
    required_secret_refs: ["secret://<env>/connector/database-read/*"],
    allowed_domains: [],
    manifest_permissions: { api: ["readConfig"], network: false, secret_refs: ["secret://<env>/connector/database-read/*"] },
    implementation_state: "blocked by browser-scope decision; no approved browser execution surface",
    security_notes: ["활성화 전에 명시적 백엔드 승인과 보안 자격증명 저장이 필요합니다."],
    created_at: "2026-06-19T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
];
