import type { CatalogStatus } from "./connector-catalog-data";

export type TemplateKind = "browser_workflow" | "api_workflow" | "file_workflow" | "notification_workflow";

export interface TemplateCatalogItem {
  catalog_id: string;
  template_id: string;
  connector_id: string;
  name: string;
  kind: TemplateKind;
  status: CatalogStatus;
  priority: "P0" | "P1" | "P2" | "P3";
  summary: string;
  best_for: readonly string[];
  required_params: readonly string[];
  required_secret_refs: readonly string[];
  produced_ir_pattern: string;
  success_criteria: string;
  created_at: string;
  updated_at: string;
}

export const TEMPLATES: readonly TemplateCatalogItem[] = [
  {
    catalog_id: "92000000-0000-4000-8000-000000000001",
    template_id: "sap-web-list-extract",
    connector_id: "sap-web",
    name: "SAP 목록 추출",
    kind: "browser_workflow",
    status: "candidate",
    priority: "P0",
    summary: "ERP 목록 화면을 열어 필터를 적용하고 행을 추출한 뒤 마스킹된 증빙을 보관합니다.",
    best_for: ["송장 상태", "발주 목록", "납품 목록"],
    required_params: ["entry_url", "filter_text", "max_pages"],
    required_secret_refs: ["secret://<env>/connector/sap-web/*"],
    produced_ir_pattern: "navigate -> act(filter) -> loop(extract rows) -> verify(row_count)",
    success_criteria: "행이 최소 1건 추출되거나 결정형 빈-상태 플래그가 관찰됩니다.",
    created_at: "2026-06-23T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000002",
    template_id: "sap-web-approval-check",
    connector_id: "sap-web",
    name: "SAP 결재 확인",
    kind: "browser_workflow",
    status: "candidate",
    priority: "P1",
    summary: "웹 결재 대기열을 확인하고 모호한 판단은 사람 확인 검증으로 넘깁니다.",
    best_for: ["결재 대기열", "예외 검토", "이중 확인"],
    required_params: ["entry_url", "document_id"],
    required_secret_refs: ["secret://<env>/connector/sap-web/*"],
    produced_ir_pattern: "navigate -> extract approval fields -> human_task(validation) when ambiguous",
    success_criteria: "판단 항목이 추출되거나 검증용 사람 확인 작업이 열립니다.",
    created_at: "2026-06-22T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000003",
    template_id: "browser-report-download",
    connector_id: "excel-csv",
    name: "브라우저 리포트 다운로드",
    kind: "file_workflow",
    status: "candidate",
    priority: "P1",
    summary: "리포트 화면으로 이동해 CSV 내보내기를 다운로드하고 마스킹 게이트를 거친 증빙으로 보관합니다.",
    best_for: ["일일 리포트", "대사 내보내기", "정산 파일"],
    required_params: ["entry_url", "report_name"],
    required_secret_refs: [],
    produced_ir_pattern: "navigate -> act(download) -> artifact(receipt) -> verify(download_complete)",
    success_criteria: "다운로드 증빙이 마스킹 상태 ‘마스킹됨(redacted)’ 또는 ‘불필요(not_required)’로 기록됩니다.",
    created_at: "2026-06-21T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000006",
    template_id: "document-idp-validation",
    connector_id: "document-idp",
    name: "문서 항목 검증",
    kind: "file_workflow",
    status: "candidate",
    priority: "P1",
    summary: "브라우저로 캡처한 텍스트/CSV/JSON 증빙에서 설정된 항목을 추출하고, 신뢰도가 낮으면 검증 작업을 엽니다.",
    best_for: ["송장 항목", "계약 메타데이터", "결재 증빙", "수기 보정 루프"],
    required_params: ["source_artifact_id", "document_type", "field_schema"],
    required_secret_refs: [],
    produced_ir_pattern: "browser artifact -> deterministic_text_v1 extract -> human_task(validation) for low confidence",
    success_criteria: "필수 항목이 추출되거나 증빙 참조가 포함된 business_form_v1 검증 작업이 열립니다.",
    created_at: "2026-06-23T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000004",
    template_id: "http-api-status-check",
    connector_id: "http-api",
    name: "HTTP 상태 확인",
    kind: "api_workflow",
    status: "requires_admin",
    priority: "P0",
    summary: "결과 확인용으로 승인된 API 상태 조회 템플릿.",
    best_for: ["상태 조회", "케이스 보강", "API 핸드오프"],
    required_params: ["endpoint_url", "method", "request_schema_ref"],
    required_secret_refs: ["secret://<env>/connector/http-api/*"],
    produced_ir_pattern: "api_call -> verify(http_status)",
    success_criteria: "설정된 2xx HTTP 상태가 관찰됩니다. 응답 스키마 검증은 향후 커넥터 프로필 계약이 필요합니다.",
    created_at: "2026-06-20T00:00:00.000Z",
    updated_at: "2026-06-23T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000007",
    template_id: "managed-idp-scim-provider-registration",
    connector_id: "managed-idp-scim",
    name: "SCIM 제공자 등록",
    kind: "api_workflow",
    status: "requires_admin",
    priority: "P0",
    summary: "보안 연결 전용 서명 메타데이터와 닫힌 회전 정책으로 관리형 IdP SCIM 제공자를 등록합니다.",
    best_for: ["신규 IdP 테넌트 온보딩", "SCIM 서명 키 등록", "제공자 준비 증빙"],
    required_params: ["provider_key", "display_name", "signature_secret_ref", "secret_rotation_policy", "clock_skew_seconds"],
    required_secret_refs: ["secret://<tenant>/scim/<provider_key>/signing"],
    produced_ir_pattern: "POST /v1/scim/providers -> provider rotation evidence",
    success_criteria: "auth_mode=signed_request_v1 로 제공자 행이 생성되고 signature_secret_ref 만 노출됩니다.",
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000008",
    template_id: "managed-idp-scim-group-role-import",
    connector_id: "managed-idp-scim",
    name: "SCIM 그룹-역할 가져오기",
    kind: "api_workflow",
    status: "requires_admin",
    priority: "P0",
    summary: "저장소가 소유한 매핑 원장을 통해 불투명한 IdP 그룹을 닫힌 RPA 역할로 일괄 가져오거나 정합합니다.",
    best_for: ["그룹 매핑 초기 구성", "주기적 접근 검토", "IdP-RPA 역할 정합"],
    required_params: ["provider_key", "mode", "mappings"],
    required_secret_refs: [],
    produced_ir_pattern: "POST /v1/scim/providers/{provider_key}/group-role-mappings/import",
    success_criteria: "응답이 외부 그룹 의미를 추론하지 않고 가져옴·갱신·변경없음·비활성 매핑 건수를 보고합니다.",
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000009",
    template_id: "managed-idp-scim-provider-decommission",
    connector_id: "managed-idp-scim",
    name: "SCIM 제공자 폐기",
    kind: "api_workflow",
    status: "requires_admin",
    priority: "P1",
    summary: "폐기된 IdP 제공자를 비활성화하고 활성 매핑을 끄며, 감사 증빙과 함께 활성 SCIM 관리 배정을 회수합니다.",
    best_for: ["IdP 테넌트 폐기", "제공자 마이그레이션 정리", "접근 회수 증빙"],
    required_params: ["provider_key", "reason"],
    required_secret_refs: [],
    produced_ir_pattern: "POST /v1/scim/providers/{provider_key}/decommission",
    success_criteria: "제공자가 비활성화되고 응답이 disabled_mappings·revoked_assignments 건수를 기록합니다.",
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000010",
    template_id: "uipath-handoff-provider-profile",
    connector_id: "existing-rpa-handoff",
    name: "UiPath 핸드오프 제공자 프로필",
    kind: "api_workflow",
    status: "requires_admin",
    priority: "P1",
    summary: "기존 RPA 원장을 위한 메타데이터 전용 UiPath 핸드오프 별칭/프로필 템플릿입니다. UiPath API/OAuth 나 큐 의미는 구현하지 않습니다.",
    best_for: ["UiPath Orchestrator 공존", "큐 핸드오프 증빙", "서명된 제공자 접수 캡처"],
    required_params: ["provider_alias", "job_ref", "payload_ref", "callback_url_secret_ref", "callback_signature_secret_ref", "endpoint_secret_ref", "allowed_hosts"],
    required_secret_refs: ["secret://<tenant>/integration/uipath/callback-url", "secret://<tenant>/integration/uipath/callback-signing", "secret://<tenant>/integration/uipath/dispatch-endpoint"],
    produced_ir_pattern: "POST /v1/integration-handoffs -> optional dispatch -> provider receipt/callback",
    success_criteria: "핸드오프 생성은 보류 상태로 유지되고, 디스패치는 ‘접수됨’만 기록하며, ‘완료’는 오너/제공자 프로필이 제공하는 UiPath 접수/회신 증빙이 필요합니다.",
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000011",
    template_id: "automation-anywhere-handoff-provider-profile",
    connector_id: "existing-rpa-handoff",
    name: "Automation Anywhere 핸드오프 제공자 프로필",
    kind: "api_workflow",
    status: "candidate",
    priority: "P1",
    summary: "메타데이터 전용 Automation Anywhere 핸드오프 별칭/프로필 템플릿입니다. Control Room API/OAuth 직접 연동은 오너/제공자 범위로 남습니다.",
    best_for: ["Automation Anywhere 공존", "Control Room 작업 증빙", "외부 봇 접수 캡처"],
    required_params: ["provider_alias", "job_ref", "payload_ref", "callback_url_secret_ref", "callback_signature_secret_ref", "endpoint_secret_ref", "allowed_hosts"],
    required_secret_refs: ["secret://<tenant>/integration/automation-anywhere/callback-url", "secret://<tenant>/integration/automation-anywhere/callback-signing", "secret://<tenant>/integration/automation-anywhere/dispatch-endpoint"],
    produced_ir_pattern: "POST /v1/integration-handoffs -> optional dispatch -> provider receipt/callback",
    success_criteria: "프로필은 메타데이터와 접수 상태만 기록하며, 실제 Automation Anywhere API/OAuth 동작은 오너/제공자 계약이 승인되기 전까지 보장하지 않습니다.",
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000012",
    template_id: "power-automate-handoff-provider-profile",
    connector_id: "existing-rpa-handoff",
    name: "Power Automate 핸드오프 제공자 프로필",
    kind: "api_workflow",
    status: "candidate",
    priority: "P1",
    summary: "메타데이터 전용 Power Automate 핸드오프 별칭/프로필 템플릿입니다. 클라우드 플로우/데스크톱 플로우 API/OAuth 직접 연동은 오너/제공자 범위로 남습니다.",
    best_for: ["Power Automate 공존", "클라우드 플로우 핸드오프 증빙", "외부 플로우 접수 캡처"],
    required_params: ["provider_alias", "job_ref", "payload_ref", "callback_url_secret_ref", "callback_signature_secret_ref", "endpoint_secret_ref", "allowed_hosts"],
    required_secret_refs: ["secret://<tenant>/integration/power-automate/callback-url", "secret://<tenant>/integration/power-automate/callback-signing", "secret://<tenant>/integration/power-automate/dispatch-endpoint"],
    produced_ir_pattern: "POST /v1/integration-handoffs -> optional dispatch -> provider receipt/callback",
    success_criteria: "프로필은 메타데이터와 접수 상태만 기록하며, 실제 Power Automate API/OAuth 동작은 오너/제공자 계약이 승인되기 전까지 보장하지 않습니다.",
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000013",
    template_id: "blue-prism-handoff-provider-profile",
    connector_id: "existing-rpa-handoff",
    name: "Blue Prism 핸드오프 제공자 프로필",
    kind: "api_workflow",
    status: "candidate",
    priority: "P1",
    summary: "메타데이터 전용 Blue Prism 핸드오프 별칭/프로필 템플릿입니다. Control Room/API/OAuth 직접 연동은 오너/제공자 범위로 남습니다.",
    best_for: ["Blue Prism 공존", "Control Room 작업 큐 증빙", "외부 프로세스 접수 캡처"],
    required_params: ["provider_alias", "job_ref", "payload_ref", "callback_url_secret_ref", "callback_signature_secret_ref", "endpoint_secret_ref", "allowed_hosts"],
    required_secret_refs: ["secret://<tenant>/integration/blue-prism/callback-url", "secret://<tenant>/integration/blue-prism/callback-signing", "secret://<tenant>/integration/blue-prism/dispatch-endpoint"],
    produced_ir_pattern: "POST /v1/integration-handoffs -> optional dispatch -> provider receipt/callback",
    success_criteria: "프로필은 메타데이터와 접수 상태만 기록하며, 실제 Blue Prism API/OAuth 동작은 오너/제공자 계약이 승인되기 전까지 보장하지 않습니다.",
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
  {
    catalog_id: "92000000-0000-4000-8000-000000000005",
    template_id: "ops-failure-alert",
    connector_id: "ops-webhook-sender",
    name: "운영 실패 알림",
    kind: "notification_workflow",
    status: "available",
    priority: "P1",
    summary: "실패한 실행·SLA 위험·사람 확인 시간초과 에스컬레이션을 위한 보안 연결 기반 범용 웹훅 알림 패턴.",
    best_for: ["실행 실패 웹훅", "SLA 위험 웹훅", "사람 확인 시간초과 웹훅"],
    required_params: ["severity", "message_template", "endpoint_secret_ref", "route_policy_ref", "allowed_hosts"],
    required_secret_refs: ["secret://<tenant>/notification-sender/webhook/<route_alias>/endpoint"],
    produced_ir_pattern: "ops event -> /v1/ops-alerts alert -> webhook send attempt -> receipt ledger",
    success_criteria: "웹훅 시도가 큐에 적재되고 발송/실패 메타데이터를 기록합니다. ‘전달됨’은 제공자 접수/회신 증빙이 필요하며 콘솔 확인만으로는 추론하지 않습니다.",
    created_at: "2026-06-29T00:00:00.000Z",
    updated_at: "2026-06-29T00:00:00.000Z",
  },
];
