import type { ApiClient } from "../src/api/client";

// 테스트용 fake ApiClient(백엔드 무의존). 뷰는 동일 포트로 주입되므로 fixture만 갈아끼운다.
export function fakeClient(overrides: Partial<ApiClient> = {}): ApiClient {
  const empty = async () => ({ items: [], next_cursor: null });
  return {
    listRuns: async () => ({
      // current_node는 reads.ts:203이 영구 null(runs에 진행-노드 컬럼 없음) → fixture도 null(백엔드가 만들 수 없는 값 미창작).
      items: [{ run_id: "11111111-aaaa-bbbb-cccc-000000000001", status: "running", priority: "medium", current_node: null, as_of: "2026-06-15T00:00:00.000Z", failure_reason: null }],
      next_cursor: null,
    }),
    listRunSteps: async () => ({
      items: [
        { step_id: "s1", node_id: "open", attempt: 0, action: "navigate", status: "success", cache_mode: "bypass", artifact_ids: [], stagehand_calls: [], started_at: null, ended_at: null, duration_ms: 820, exception: null },
        { step_id: "s2", node_id: "extract", attempt: 0, action: "extract", status: "success", cache_mode: "hit", artifact_ids: ["72000000-0000-0000-0000-000000000001"], stagehand_calls: [{ model: "gpt-4o-mini", transport: "sse", stream_status: "done", ttfb_ms: 120, input_tokens: 500, output_tokens: 200, cost: "0.001234" }], started_at: null, ended_at: null, duration_ms: 1200, exception: null },
      ],
      next_cursor: null,
    }),
    watchRunSteps: () => () => undefined,
    listRunArtifacts: async () => ({
      items: [
        { artifact_id: "72000000-0000-0000-0000-0000000000ff", type: "screen_capture", media_type: "image/png", filename: "screen.png", byte_size: 1024, duration_ms: null, redaction_status: "redacted", retention_until: "2026-09-01T00:00:00.000Z", legal_hold: false, created_at: "2026-06-15T00:00:01.000Z" },
        { artifact_id: "72000000-0000-0000-0000-000000000001", type: "extract_result_json", media_type: "application/json", filename: "invoice-data.json", byte_size: 2048, duration_ms: null, redaction_status: "redacted", retention_until: "2026-09-01T00:00:00.000Z", legal_hold: false, created_at: "2026-06-15T00:00:02.000Z" },
      ],
      next_cursor: null,
    }),
    listScenarioGenerationArtifacts: empty,
    listScenarioGenerationResultArtifacts: empty,
    listWorkitems: empty,
    listHumanTasks: empty,
    listPrincipals: empty,
    listDlq: empty,
    listScenarios: empty,
    search: async () => ({ items: [], next_cursor: null }),
    listRunTriggers: empty,
    createRunTrigger: async (body) => ({
      trigger_id: "00000000-0000-0000-0000-00000000f001",
      scenario_version_id: body.scenario_version_id,
      trigger_type: body.trigger_type ?? "cron",
      status: "enabled",
      cron_expression: body.trigger_type === "webhook" ? null : body.cron_expression ?? "0 9 * * 1-5",
      timezone: body.trigger_type === "webhook" ? null : body.timezone ?? "Asia/Seoul",
      webhook_secret_ref: body.webhook_secret_ref ?? null,
      params: body.params ?? {},
      catchup_policy: body.catchup_policy ?? "skip_missed",
      max_concurrent_runs: body.max_concurrent_runs ?? 1,
      next_fire_at: body.next_fire_at ?? null,
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:00.000Z",
    }),
    updateRunTrigger: async (triggerId, body) => ({
      trigger_id: triggerId,
      scenario_version_id: "00000000-0000-0000-0000-0000000000c2",
      trigger_type: body.webhook_secret_ref !== undefined ? "webhook" : "cron",
      status: "enabled",
      cron_expression: body.webhook_secret_ref !== undefined ? null : body.cron_expression ?? "0 9 * * 1-5",
      timezone: body.webhook_secret_ref !== undefined ? null : body.timezone ?? "Asia/Seoul",
      webhook_secret_ref: body.webhook_secret_ref ?? null,
      params: body.params ?? {},
      catchup_policy: body.catchup_policy ?? "skip_missed",
      max_concurrent_runs: body.max_concurrent_runs ?? 1,
      next_fire_at: body.next_fire_at ?? null,
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:01.000Z",
    }),
    pauseRunTrigger: async (triggerId) => ({
      trigger_id: triggerId,
      scenario_version_id: "00000000-0000-0000-0000-0000000000c2",
      trigger_type: "cron",
      status: "paused",
      cron_expression: "0 9 * * 1-5",
      timezone: "Asia/Seoul",
      webhook_secret_ref: null,
      params: {},
      catchup_policy: "skip_missed",
      max_concurrent_runs: 1,
      next_fire_at: null,
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:01.000Z",
    }),
    resumeRunTrigger: async (triggerId) => ({
      trigger_id: triggerId,
      scenario_version_id: "00000000-0000-0000-0000-0000000000c2",
      trigger_type: "cron",
      status: "enabled",
      cron_expression: "0 9 * * 1-5",
      timezone: "Asia/Seoul",
      webhook_secret_ref: null,
      params: {},
      catchup_policy: "skip_missed",
      max_concurrent_runs: 1,
      next_fire_at: null,
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:01.000Z",
    }),
    listRunTriggerFires: empty,
    getRunTrigger: async (triggerId) => ({
      trigger_id: triggerId,
      scenario_version_id: "00000000-0000-0000-0000-0000000000c2",
      trigger_type: "cron",
      status: "enabled",
      cron_expression: "0 9 * * 1-5",
      timezone: "Asia/Seoul",
      webhook_secret_ref: null,
      params: {},
      catchup_policy: "skip_missed",
      max_concurrent_runs: 1,
      next_fire_at: null,
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:00.000Z",
    }),
    listOpsAlerts: empty,
    getOpsHealth: async () => ({
      status: "ok",
      detected_at: "2026-06-23T00:00:00.000Z",
      queue: { available: false, pending_jobs: null },
      browser_leases: { reserved: 0, active: 0, draining: 0, expired: 0, expired_open: 0, next_expiry_at: null },
      stale_runs: { nonterminal_over_15m: 0, oldest_updated_at: null },
    }),
    listBotPools: async () => ({
      items: [
        {
          bot_pool_id: "browser-default",
          name: "브라우저 실행 풀",
          kind: "browser",
          capacity_slots: 1,
          workers: { total: 1, active: 1, draining: 0, dead: 0, stale: 0, open_circuit: 0 },
          leases: { reserved: 0, active: 0, draining: 0, expired_open: 0, next_expiry_at: null },
          queue: { pending_runs: 0, queued_runs: 0, claimed_runs: 0, oldest_queued_at: null, due_triggers: 0 },
          capacity: {
            occupied_slots: 0,
            available_slots: 1,
            capacity_gap: 0,
            queue_pressure: 0,
            live_capacity: { available: false, reason_code: "worker_pool_membership_missing" },
          },
          health: "ok",
          health_reason: "브라우저 실행 용량이 정상 범위입니다.",
        },
      ],
      next_cursor: null,
    }),
    getAutomationPerformanceReport: async () => ({
      month: "2026-06",
      timezone: "Asia/Seoul",
      period_start: "2026-05-31T15:00:00.000Z",
      period_end: "2026-06-30T15:00:00.000Z",
      summary: {
        total_runs: 12,
        completed: 9,
        failed_business: 2,
        failed_system: 1,
        success_rate: 0.75,
        rerun_count: 2,
        reprocessing_rate: 0.16666666666666666,
        estimated_hours_saved: 18.5,
        estimated_value: 740000,
        implementation_effort: 900000,
        net_value: 739987.66,
        value_to_cost_ratio: 59967.58508914101,
        payback_months: 1.2162162162162162,
        gateway_cost: 12.34,
        cost_by_status: { completed: 8.34, failed_business: 2, failed_system: 2, other: 0 },
        failed_cost: 4,
        rerun_cost: 1.5,
        avg_cost_per_run: 1.0283333333333333,
        cost_per_completed_run: 0.9266666666666666,
        llm_call_cost: 11.5,
        run_vs_call_cost_delta: 0.84,
        roi_idea_count: 1,
        roi_confidence: { low: 0, medium: 0, high: 1 },
      },
      cost_by_model: [
        { model: "gpt-4o-mini", calls: 12, input_tokens: 24000, output_tokens: 4200, cost: 11.5, cost_share: 1 },
      ],
      failure_top: [{ code: "SITE_SELECTOR_MISSING", count: 2 }],
      by_workflow: [
        {
          scenario_id: "00000000-0000-4000-8000-0000000000a1",
          scenario_name: "Vendor invoice lookup",
          total_runs: 12,
          completed: 9,
          failed_business: 2,
          failed_system: 1,
          success_rate: 0.75,
          rerun_count: 2,
          reprocessing_rate: 0.16666666666666666,
          estimated_hours_saved: 18.5,
          estimated_value: 740000,
          implementation_effort: 900000,
          net_value: 739987.66,
          value_to_cost_ratio: 59967.58508914101,
          payback_months: 1.2162162162162162,
          gateway_cost: 12.34,
          cost_by_status: { completed: 8.34, failed_business: 2, failed_system: 2, other: 0 },
          rerun_cost: 1.5,
          avg_cost_per_run: 1.0283333333333333,
          cost_per_completed_run: 0.9266666666666666,
          roi_idea_count: 1,
          roi_confidence: { low: 0, medium: 0, high: 1 },
        },
      ],
      trends: [],
    }),
    exportAutomationPerformanceReportCsv: async () => "Summary\nmetric,value\nmonth,2026-06\n",
    listAuditLog: async (p) => ({
      items: [
        p?.action === "secret.resolve"
          ? {
            audit_id: "81000000-0000-4000-8000-0000000000b1",
            sequence_no: 3,
            actor: { subject_id: "runner-a", roles: ["operator"] },
            action: "secret.resolve",
            outcome: "allow",
            reason: "secret resolved",
            correlation_id: "82000000-0000-4000-8000-0000000000b1",
            idempotency_key: "audit-fixture-secret-1",
            occurred_at: "2026-06-23T09:05:00.000Z",
            payload_schema_ref: "audit/secret-resolve@1",
            retention_until: "2026-09-23T09:05:00.000Z",
            legal_hold: false,
            previous_hash: "sha256:new",
            hash: "sha256:secret",
            created_at: "2026-06-23T09:05:01.000Z",
          }
          : {
            audit_id: "81000000-0000-4000-8000-0000000000a1",
            sequence_no: 2,
            actor: { subject_id: "viewer-a", roles: ["viewer"] },
            action: "artifact.read",
            outcome: "allow",
            reason: "artifact disclosed",
            correlation_id: "82000000-0000-4000-8000-0000000000a1",
            idempotency_key: "audit-fixture-1",
            occurred_at: "2026-06-23T09:00:00.000Z",
            payload_schema_ref: "audit/security-boundary-decision@1",
            retention_until: "2026-09-23T09:00:00.000Z",
            legal_hold: false,
            previous_hash: "sha256:old",
            hash: "sha256:new",
            created_at: "2026-06-23T09:00:01.000Z",
          },
      ],
      next_cursor: null,
    }),
    exportAuditLogCsv: async () => "audit_id,sequence_no,action,outcome\n81000000-0000-4000-8000-0000000000a1,2,artifact.read,allow\n",
    getAuthReadiness: async () => ({
      status: "ok",
      enterprise_sso_ready: true,
      provider: {
        mode: "jwks",
        configuration_source: "deployment_config",
        algorithm: "RS256",
        jwks_url_configured: true,
        jwks_host: "idp.example.com",
        issuer_configured: true,
        issuer: "https://idp.example.com/",
        audience_configured: true,
        audience: "rpa-console",
      },
      claim_mapping: {
        subject_claim: "sub",
        tenant_claim: "tenant_id",
        roles_claim: "roles",
        expiry_claim: "exp",
        display_name_claim: "name",
        email_claim: "email",
      },
      role_mapping: {
        configured: false,
        mapped_values: 0,
      },
      required_claims: [
        { claim: "sub", label: "처리자 식별", required: true, present: true, mapped_to: "current_principal.subject_id" },
        { claim: "tenant_id", label: "테넌트 경계", required: true, present: true, mapped_to: "current_principal.tenant_id" },
        { claim: "roles", label: "역할 매핑", required: true, present: true, mapped_to: "current_principal.roles" },
        { claim: "exp", label: "만료 시간", required: true, present: true, mapped_to: "인증 만료 검증" },
        { claim: "name", label: "표시 이름", required: false, present: true, mapped_to: "담당자 디렉터리 표시명" },
        { claim: "email", label: "이메일", required: false, present: true, mapped_to: "담당자 디렉터리 이메일" },
      ],
      current_principal: {
        subject_id: "viewer-a",
        tenant_id: "00000000-0000-4000-8000-0000000000a1",
        roles: ["viewer"],
        source: "jwt",
        display_name: "Viewer A",
        email: "viewer@example.com",
      },
      operational_gaps: [],
    }),
    listConnectors: async () => ({
      items: [
        {
          catalog_id: "90000000-0000-4000-8000-000000000001",
          connector_id: "sap-web",
          name: "SAP Web / ERP Portal",
          kind: "browser",
          category: "ERP",
          status: "candidate",
          priority: "P0",
          summary: "Browser-first SAP portal automation pattern for DOM-backed ERP pages.",
          best_for: ["vendor balance lookup", "approval status check"],
          supported_actions: ["navigate", "click", "extract", "download"],
          template_ids: ["sap-web-list-extract"],
          required_rbac_actions: ["connector.read", "site.read", "scenario.create"],
          required_secret_refs: ["secret://sites/sap-web/session"],
          allowed_domains: ["https://sap.example.com"],
          manifest_permissions: { api: ["readConfig"], network: false, secret_refs: ["secret://sites/sap-web/session"] },
          implementation_state: "browser template pack for approved web portals",
          security_notes: ["Uses stored browser session references only."],
          created_at: "2026-06-23T00:00:00.000Z",
          updated_at: "2026-06-23T00:00:00.000Z",
        },
        {
          catalog_id: "90000000-0000-4000-8000-000000000002",
          connector_id: "http-api",
          name: "HTTP API",
          kind: "api",
          category: "Integration",
          status: "requires_admin",
          priority: "P0",
          summary: "Metadata placeholder for approved HTTP integration templates.",
          best_for: ["status lookup", "system-to-system handoff"],
          supported_actions: ["request", "parse_json"],
          template_ids: ["http-api-status-check"],
          required_rbac_actions: ["connector.read", "connector.enable"],
          required_secret_refs: ["secret://connectors/http-api/*"],
          allowed_domains: [],
          manifest_permissions: { api: ["readConfig"], network: false, secret_refs: ["secret://connectors/http-api/*"] },
          implementation_state: "blocked_by_executor_capability",
          security_notes: ["Connector execution requires an explicit backend capability contract."],
          created_at: "2026-06-23T00:00:00.000Z",
          updated_at: "2026-06-23T00:00:00.000Z",
        },
        {
          catalog_id: "90000000-0000-4000-8000-000000000006",
          connector_id: "document-idp",
          name: "Document IDP (Browser Artifacts)",
          kind: "file",
          category: "Document Automation",
          status: "candidate",
          priority: "P1",
          summary: "Built-in deterministic document extraction and validation templates for redaction-visible browser artifacts.",
          best_for: ["invoice review", "contract field check", "validation queue"],
          supported_actions: ["artifact", "extract", "human_task", "verify"],
          template_ids: ["document-idp-validation"],
          required_rbac_actions: ["connector.read", "artifact.read", "human_task.read", "scenario.create"],
          required_secret_refs: [],
          allowed_domains: ["reports.example.com", "vendor.example.com"],
          manifest_permissions: { api: ["readConfig"], network: false, secret_refs: [] },
          implementation_state: "P1 engine: built_in_deterministic_text_v1 over redaction-visible text/CSV/JSON artifacts; OCR and image decoding require a future document adapter",
          security_notes: [
            "Document bytes stay inside the tenant boundary in P1.",
            "Artifact body access still uses the existing artifact redaction, RBAC, and audit gates.",
          ],
          created_at: "2026-06-23T00:00:00.000Z",
          updated_at: "2026-06-23T00:00:00.000Z",
        },
      ],
      next_cursor: null,
    }),
    listTemplates: async () => ({
      items: [
        {
          catalog_id: "91000000-0000-4000-8000-000000000001",
          template_id: "sap-web-list-extract",
          connector_id: "sap-web",
          name: "SAP list extract",
          kind: "browser_workflow",
          status: "available",
          priority: "P0",
          summary: "Open SAP web list, apply filters, extract visible table rows, and store redacted evidence.",
          best_for: ["monthly vendor reconciliation"],
          required_params: ["start_url", "date_range", "company_code"],
          required_secret_refs: ["secret://sites/sap-web/session"],
          produced_ir_pattern: "browser_extract_table",
          success_criteria: "table rows extracted; screenshot evidence stored",
          created_at: "2026-06-23T00:00:00.000Z",
          updated_at: "2026-06-23T00:00:00.000Z",
        },
        {
          catalog_id: "91000000-0000-4000-8000-000000000002",
          template_id: "http-api-status-check",
          connector_id: "http-api",
          name: "HTTP status check",
          kind: "api_workflow",
          status: "requires_admin",
          priority: "P0",
          summary: "Call an approved HTTP endpoint and validate a status field once API execution is contracted.",
          best_for: ["external system health lookup"],
          required_params: ["endpoint_profile_id", "status_path"],
          required_secret_refs: ["secret://connectors/http-api/*"],
          produced_ir_pattern: "api_call_validate_json",
          success_criteria: "response status is accepted",
          created_at: "2026-06-23T00:00:00.000Z",
          updated_at: "2026-06-23T00:00:00.000Z",
        },
        {
          catalog_id: "91000000-0000-4000-8000-000000000006",
          template_id: "document-idp-validation",
          connector_id: "document-idp",
          name: "Document field validation",
          kind: "file_workflow",
          status: "candidate",
          priority: "P1",
          summary: "Extract configured fields from browser-captured text/CSV/JSON artifacts and open a validation task when confidence is low.",
          best_for: ["invoice fields", "contract metadata", "manual correction loop"],
          required_params: ["source_artifact_id", "document_type", "field_schema"],
          required_secret_refs: [],
          produced_ir_pattern: "browser artifact -> deterministic_text_v1 extract -> human_task(validation) for low confidence",
          success_criteria: "Required fields are extracted or a business_form_v1 validation task is opened with artifact references.",
          created_at: "2026-06-23T00:00:00.000Z",
          updated_at: "2026-06-23T00:00:00.000Z",
        },
      ],
      next_cursor: null,
    }),
    listDocumentJobs: async () => ({
      items: [
        {
          document_job_id: "93000000-0000-4000-8000-000000000001",
          source_artifact_id: "72000000-0000-0000-0000-000000000001",
          source_run_id: "11111111-aaaa-bbbb-cccc-000000000001",
          document_type: "invoice",
          field_schema: [
            { key: "invoice_id", label: "송장 번호", required: true, type: "text", aliases: ["Invoice ID"], min_confidence: 0.8 },
            { key: "total", label: "금액", required: true, type: "number", aliases: ["Total"], min_confidence: 0.8 },
            { key: "approved", label: "승인 여부", required: false, type: "boolean", min_confidence: 0.7 },
          ],
          status: "validation_required",
          created_by: "operator",
          created_at: "2026-06-23T09:00:00.000Z",
          updated_at: "2026-06-23T09:00:03.000Z",
        },
        {
          document_job_id: "93000000-0000-4000-8000-000000000002",
          source_artifact_id: "72000000-0000-0000-0000-000000000002",
          source_run_id: "11111111-aaaa-bbbb-cccc-000000000001",
          document_type: "contract",
          field_schema: [
            { key: "contract_no", label: "계약 번호", required: true, type: "text", min_confidence: 0.8 },
            { key: "counterparty", label: "거래처", required: true, type: "text", min_confidence: 0.8 },
          ],
          status: "extracted",
          created_by: "operator",
          created_at: "2026-06-23T08:40:00.000Z",
          updated_at: "2026-06-23T08:40:04.000Z",
        },
      ],
      next_cursor: null,
    }),
    createDocumentJob: async (body) => ({
      document_job_id: "93000000-0000-4000-8000-000000000099",
      source_artifact_id: body.source_artifact_id,
      source_run_id: "11111111-aaaa-bbbb-cccc-000000000001",
      document_type: body.document_type,
      field_schema: body.field_schema,
      status: "created",
      created_by: "operator",
      created_at: "2026-06-23T09:10:00.000Z",
      updated_at: "2026-06-23T09:10:00.000Z",
    }),
    getDocumentJob: async (jobId) => ({
      document_job_id: jobId,
      source_artifact_id: "72000000-0000-0000-0000-000000000001",
      source_run_id: "11111111-aaaa-bbbb-cccc-000000000001",
      document_type: "invoice",
      field_schema: [
        { key: "invoice_id", label: "송장 번호", required: true, type: "text", min_confidence: 0.8 },
        { key: "total", label: "금액", required: true, type: "number", min_confidence: 0.8 },
      ],
      status: "validation_required",
      created_by: "operator",
      created_at: "2026-06-23T09:00:00.000Z",
      updated_at: "2026-06-23T09:00:03.000Z",
    }),
    extractDocumentJob: async (jobId) => ({
      document_extraction_id: "94000000-0000-4000-8000-000000000001",
      document_job_id: jobId,
      engine: "built_in_deterministic_text_v1",
      status: "validation_required",
      fields: [
        { key: "invoice_id", label: "송장 번호", value: "INV-7", confidence: 0.78, status: "low_confidence", source: "label" },
        { key: "total", label: "금액", value: "9900", confidence: 0.78, status: "low_confidence", source: "label" },
      ],
      missing_fields: ["invoice_id", "total"],
      validation_human_task_id: null,
      created_at: "2026-06-23T09:00:03.000Z",
      updated_at: "2026-06-23T09:00:03.000Z",
    }),
    getDocumentExtraction: async (jobId) => ({
      document_extraction_id: "94000000-0000-4000-8000-000000000001",
      document_job_id: jobId,
      engine: "built_in_deterministic_text_v1",
      status: "validation_required",
      fields: [
        { key: "invoice_id", label: "송장 번호", value: "INV-7", confidence: 0.78, status: "low_confidence", source: "label" },
        { key: "total", label: "금액", value: "9900", confidence: 0.78, status: "low_confidence", source: "label" },
      ],
      missing_fields: ["invoice_id", "total"],
      validation_human_task_id: "55000000-0000-0000-0000-000000000055",
      created_at: "2026-06-23T09:00:03.000Z",
      updated_at: "2026-06-23T09:00:04.000Z",
    }),
    createDocumentValidationTask: async () => ({
      human_task_id: "55000000-0000-0000-0000-000000000055",
      state: "open",
      result_schema: {
        version: "business_form_v1",
        fields: [
          { key: "invoice_id", label: "송장 번호", type: "text", required: true },
          { key: "total", label: "금액", type: "number", required: true },
        ],
      },
      artifact_refs: ["72000000-0000-0000-0000-000000000001"],
    }),
    listAutomationIdeas: async () => ({
      items: [
        {
          idea_id: "61000000-0000-4000-8000-000000000001",
          title: "거래처 포털 지급 상태 확인",
          description: "거래처 포털에서 지급 상태를 확인하고 예외만 재무 운영팀에 전달합니다.",
          business_owner: "finance-ops",
          department: "재무",
          source: "manual",
          stage: "intake",
          priority: "high",
          score: 82,
          scenario_id: null,
          run_trigger_id: null,
          created_by: "operator",
          created_at: "2026-06-15T00:00:00.000Z",
          updated_at: "2026-06-15T00:00:00.000Z",
        },
      ],
      next_cursor: null,
    }),
    createAutomationIdea: async (body) => ({
      idea_id: "61000000-0000-4000-8000-000000000099",
      title: body.title,
      description: body.description,
      business_owner: body.business_owner,
      department: body.department,
      source: body.source ?? "manual",
      stage: "intake",
      priority: body.priority ?? "medium",
      score: body.score ?? 0,
      scenario_id: null,
      run_trigger_id: null,
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:00.000Z",
    }),
    getAutomationIdea: async (ideaId) => ({
      idea_id: ideaId,
      title: "거래처 포털 지급 상태 확인",
      description: "거래처 포털에서 지급 상태를 확인하고 예외만 재무 운영팀에 전달합니다.",
      business_owner: "finance-ops",
      department: "재무",
      source: "manual",
      stage: "intake",
      priority: "high",
      score: 82,
      scenario_id: null,
      run_trigger_id: null,
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:00.000Z",
    }),
    updateAutomationIdea: async (ideaId, body) => ({
      idea_id: ideaId,
      title: body.title ?? "거래처 포털 지급 상태 확인",
      description: body.description ?? "거래처 포털에서 지급 상태를 확인하고 예외만 재무 운영팀에 전달합니다.",
      business_owner: body.business_owner ?? "finance-ops",
      department: body.department ?? "재무",
      source: "manual",
      stage: "intake",
      priority: body.priority ?? "high",
      score: body.score ?? 82,
      scenario_id: body.scenario_id ?? null,
      run_trigger_id: body.run_trigger_id ?? null,
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:01.000Z",
    }),
    transitionAutomationIdea: async (ideaId, stage) => ({
      idea_id: ideaId,
      title: "거래처 포털 지급 상태 확인",
      description: "거래처 포털에서 지급 상태를 확인하고 예외만 재무 운영팀에 전달합니다.",
      business_owner: "finance-ops",
      department: "재무",
      source: "manual",
      stage,
      priority: "high",
      score: 82,
      scenario_id: null,
      run_trigger_id: null,
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:01.000Z",
    }),
    upsertRoiEstimate: async (ideaId, body) => {
      const monthly_hours_saved = (body.frequency_per_month * body.minutes_per_case * (1 - body.exception_rate)) / 60;
      const estimated_monthly_value = monthly_hours_saved * body.hourly_cost;
      return {
        roi_estimate_id: "62000000-0000-4000-8000-000000000001",
        automation_idea_id: ideaId,
        frequency_per_month: body.frequency_per_month,
        minutes_per_case: body.minutes_per_case,
        exception_rate: body.exception_rate,
        hourly_cost: body.hourly_cost,
        implementation_effort: body.implementation_effort,
        monthly_hours_saved,
        estimated_monthly_value,
        payback_months: estimated_monthly_value > 0 ? body.implementation_effort / estimated_monthly_value : null,
        confidence: body.confidence ?? "medium",
        created_by: "operator",
        created_at: "2026-06-15T00:00:00.000Z",
        updated_at: "2026-06-15T00:00:00.000Z",
      };
    },
    getRoiEstimate: async (ideaId) => ({
      roi_estimate_id: "62000000-0000-4000-8000-000000000001",
      automation_idea_id: ideaId,
      frequency_per_month: 120,
      minutes_per_case: 8,
      exception_rate: 0.1,
      hourly_cost: 40000,
      implementation_effort: 3200000,
      monthly_hours_saved: 14.4,
      estimated_monthly_value: 576000,
      payback_months: 5.56,
      confidence: "medium",
      created_by: "operator",
      created_at: "2026-06-15T00:00:00.000Z",
      updated_at: "2026-06-15T00:00:00.000Z",
    }),
    listSiteElements: async () => ({
      items: [
        {
          element_id: "93000000-0000-4000-8000-000000000001",
          site_profile_id: "30000000-0000-4000-8000-000000000001",
          element_key: "SubmitButton",
          label: "제출 버튼",
          selector: "button[type=submit]",
          element_type: "button",
          stability: "stable",
          source: "manual",
          sample_url: "https://portal.example.com/form",
          notes: "결재 제출 플로우에서 공유",
          usage_count: 3,
          last_verified_at: "2026-06-23T00:00:00.000Z",
          updated_by: "operator",
          created_at: "2026-06-23T00:00:00.000Z",
          updated_at: "2026-06-23T00:00:00.000Z",
        },
      ],
      next_cursor: null,
    }),
    createSiteElement: async (siteId, body) => ({
      element_id: "93000000-0000-4000-8000-000000000099",
      site_profile_id: siteId,
      element_key: body.element_key,
      label: body.label,
      selector: body.selector,
      element_type: body.element_type ?? "other",
      stability: body.stability ?? "stable",
      source: body.source ?? "manual",
      sample_url: body.sample_url ?? null,
      notes: body.notes ?? null,
      usage_count: 0,
      last_verified_at: null,
      updated_by: "operator",
      created_at: "2026-06-23T00:00:00.000Z",
      updated_at: "2026-06-23T00:00:00.000Z",
    }),
    updateSiteElement: async (siteId, elementId, body) => ({
      element_id: elementId,
      site_profile_id: siteId,
      element_key: "SubmitButton",
      label: body.label ?? "제출 버튼",
      selector: body.selector ?? "button[type=submit]",
      element_type: body.element_type ?? "button",
      stability: body.stability ?? "stable",
      source: "manual",
      sample_url: body.sample_url ?? "https://portal.example.com/form",
      notes: body.notes ?? "결재 제출 플로우에서 공유",
      usage_count: 3,
      last_verified_at: null,
      updated_by: "operator",
      created_at: "2026-06-23T00:00:00.000Z",
      updated_at: "2026-06-23T00:00:01.000Z",
    }),
    probeSiteElement: async (siteId, elementId, body) => {
      const element = {
        element_id: elementId,
        site_profile_id: siteId,
        element_key: "SubmitButton",
        label: "?쒖텧 踰꾪듉",
        selector: "button[type=submit]",
        element_type: "button" as const,
        stability: "stable" as const,
        source: "manual" as const,
        sample_url: body.sample_url ?? "https://portal.example.com/form",
        notes: "寃곗옱 ?쒖텧 ?뚮줈?곗뿉??怨듭쑀",
        usage_count: 3,
        last_verified_at: "2026-06-23T00:00:00.000Z",
        updated_by: "operator",
        created_at: "2026-06-23T00:00:00.000Z",
        updated_at: "2026-06-23T00:00:01.000Z",
      };
      return {
        element_id: elementId,
        site_profile_id: siteId,
        selector: element.selector,
        sample_url: element.sample_url,
        probe_status: "matched",
        match_count: 1,
        reason_code: null,
        checked_at: "2026-06-23T00:00:01.000Z",
        element,
      };
    },
    deleteSiteElement: async (siteId, elementId) => ({ element_id: elementId, deleted: siteId.length > 0 }),
    listBrowserRecordings: empty,
    startBrowserRecording: async (siteId, body) => ({
      recording_session_id: "94000000-0000-4000-8000-000000000001",
      site_profile_id: siteId,
      name: body.name,
      start_url: body.start_url ?? "https://portal.example.com/",
      status: "recording",
      event_count: 0,
      draft_ir: null,
      validation_report: null,
      updated_by: "operator",
      created_at: "2026-06-23T00:00:00.000Z",
      updated_at: "2026-06-23T00:00:00.000Z",
    }),
    listBrowserRecordingEvents: empty,
    appendBrowserRecordingEvents: async (_siteId, recordingId, body) => ({
      recording_session_id: recordingId,
      appended: body.events.length,
      event_count: body.events.length,
    }),
    completeBrowserRecording: async (siteId, recordingId) => ({
      recording_session_id: recordingId,
      site_profile_id: siteId,
      name: "Recorded workflow",
      start_url: "https://portal.example.com/",
      status: "completed",
      event_count: 1,
      draft_ir: { meta: { name: "Recorded workflow", version: 1 }, start: "step_01", nodes: { step_01: { action: "act" }, done: { terminal: "success" } } },
      validation_report: { errors: [], warnings: [] },
      updated_by: "operator",
      created_at: "2026-06-23T00:00:00.000Z",
      updated_at: "2026-06-23T00:00:01.000Z",
    }),
    listSites: empty,
    listSessionCaptures: empty,
    listGatewayPolicies: async () => ({
      items: [
        { model: "gpt-4o-mini", version: 1, capabilities: { jsonMode: true }, budget: { maxInputTokens: 1000 }, is_default: true },
      ],
      next_cursor: null,
    }),
    getGatewayPolicy: async () => ({ model: "gpt-4o-mini", version: 1, capabilities: { jsonMode: true }, budget: { maxInputTokens: 1000 } }),
    createGatewayPolicy: async (body) => ({ model: body.model, version: 1, capabilities: body.capabilities, budget: body.budget, fallback: body.fallback_config ?? null, is_default: body.is_default ?? false }),
    updateGatewayPolicy: async (version) => ({ model: "gpt-4o-mini", version: version + 1 }),
    deleteGatewayPolicy: async (model) => ({ model, deleted: true }),
    getGatewayCallSummary: async () => ({ window_days: 30, total: { calls: 0, input_tokens: null, output_tokens: null, cost: null }, by_model: [] }),
    abortRun: async () => ({ status: "cancelled" }),
    rerunRun: async (runId, body) => ({
      rerun_id: "77000000-0000-0000-0000-000000000001",
      source_run_id: runId,
      run_id: "77000000-0000-0000-0000-000000000002",
      status: "queued",
      mode: body.mode,
      as_of: "2026-06-26T00:00:00.000Z",
    }),
    resumeRun: async (runId) => ({
      run_id: runId,
      status: "resume_requested",
      previous_status: "suspended",
    }),
    prioritizeRun: async (runId, body) => ({
      run_id: runId,
      status: "queued",
      previous_priority: "medium",
      priority: body.priority,
    }),
    replayDeadLetter: async () => ({ status: "new" }),
    replayAllDlq: async (kind) => ({ kind, attempted: 0, replayed: 0, conflicts: 0, truncated: false }),
    assignHumanTask: async () => ({ status: "assigned" }),
    startHumanTask: async () => ({ status: "in_progress" }),
    resolveHumanTask: async () => ({ status: "resolved" }),
    escalateHumanTask: async () => ({ status: "escalated" }),
    promoteScenario: async () => ({ version: 2, promotion_status: "prod" }),
    promoteScenarioFromRun: async (scenarioId) => ({
      scenario_id: scenarioId,
      version: 2,
      scenario_version_id: "00000000-0000-0000-0000-0000000000c3",
      promotion_status: "draft",
      promoted_node_ids: ["open"],
      skipped: [],
    }),
    setScenarioPromotion: async (_scenarioId, version, target) => ({ version, promotion_status: target }),
    listScenarioEnvironmentBindings: async (scenarioId) => ({
      items: [
        {
          binding_id: "65000000-0000-4000-8000-000000000001",
          scenario_id: scenarioId,
          environment: "prod" as const,
          scenario_version_id: "00000000-0000-0000-0000-0000000000c2",
          version: 1,
          release_id: "66000000-0000-4000-8000-000000000001",
          activated_by: "admin-a",
          activated_at: "2026-06-24T00:00:00.000Z",
        },
      ],
      next_cursor: null,
    }),
    listScenarioReleases: async (scenarioId) => ({
      items: [
        {
          release_id: "66000000-0000-4000-8000-000000000001",
          scenario_id: scenarioId,
          source_version_id: "00000000-0000-0000-0000-0000000000c2",
          source_version: 1,
          target_environment: "prod" as const,
          status: "deployed" as const,
          package_hash: "sha256:release-fixture",
          validation_report: { errors: [], warnings: [] },
          requested_by: "operator-a",
          requested_at: "2026-06-24T00:00:00.000Z",
          submitted_at: "2026-06-24T00:01:00.000Z",
          approved_by: "admin-a",
          approved_at: "2026-06-24T00:02:00.000Z",
          rejected_by: null,
          rejected_at: null,
          rejection_reason: null,
          deployed_by: "admin-a",
          deployed_at: "2026-06-24T00:03:00.000Z",
          rollback_of_release_id: null,
          reason: "console release request",
          created_at: "2026-06-24T00:00:00.000Z",
          updated_at: "2026-06-24T00:03:00.000Z",
        },
      ],
      next_cursor: null,
    }),
    createScenarioRelease: async (scenarioId, body) => ({
      release_id: "66000000-0000-4000-8000-000000000099",
      scenario_id: scenarioId,
      source_version_id: "00000000-0000-0000-0000-0000000000c2",
      source_version: body.source_version,
      target_environment: body.target_environment,
      status: "draft" as const,
      package_hash: "sha256:release-draft",
      validation_report: { errors: [], warnings: [] },
      requested_by: "operator-a",
      requested_at: "2026-06-24T00:10:00.000Z",
      submitted_at: null,
      approved_by: null,
      approved_at: null,
      rejected_by: null,
      rejected_at: null,
      rejection_reason: null,
      deployed_by: null,
      deployed_at: null,
      rollback_of_release_id: null,
      reason: body.reason ?? null,
      created_at: "2026-06-24T00:10:00.000Z",
      updated_at: "2026-06-24T00:10:00.000Z",
    }),
    getScenarioRelease: async (releaseId) => ({
      release_id: releaseId,
      scenario_id: "00000000-0000-0000-0000-0000000000c1",
      source_version_id: "00000000-0000-0000-0000-0000000000c2",
      source_version: 1,
      target_environment: "prod" as const,
      status: "submitted" as const,
      package_hash: "sha256:release-fixture",
      validation_report: { errors: [], warnings: [] },
      requested_by: "operator-a",
      requested_at: "2026-06-24T00:00:00.000Z",
      submitted_at: "2026-06-24T00:01:00.000Z",
      approved_by: null,
      approved_at: null,
      rejected_by: null,
      rejected_at: null,
      rejection_reason: null,
      deployed_by: null,
      deployed_at: null,
      rollback_of_release_id: null,
      reason: "console release request",
      created_at: "2026-06-24T00:00:00.000Z",
      updated_at: "2026-06-24T00:01:00.000Z",
    }),
    submitScenarioRelease: async (releaseId) => ({
      ...(await fakeClient().getScenarioRelease(releaseId)),
      status: "submitted" as const,
      submitted_at: "2026-06-24T00:01:00.000Z",
    }),
    approveScenarioRelease: async (releaseId) => ({
      ...(await fakeClient().getScenarioRelease(releaseId)),
      status: "approved" as const,
      approved_by: "admin-a",
      approved_at: "2026-06-24T00:02:00.000Z",
    }),
    rejectScenarioRelease: async (releaseId, reason) => ({
      ...(await fakeClient().getScenarioRelease(releaseId)),
      status: "rejected" as const,
      rejected_by: "admin-a",
      rejected_at: "2026-06-24T00:02:00.000Z",
      rejection_reason: reason,
    }),
    deployScenarioRelease: async (releaseId) => ({
      ...(await fakeClient().getScenarioRelease(releaseId)),
      status: "deployed" as const,
      approved_by: "admin-a",
      approved_at: "2026-06-24T00:02:00.000Z",
      deployed_by: "admin-a",
      deployed_at: "2026-06-24T00:03:00.000Z",
    }),
    rollbackScenarioRelease: async (releaseId) => ({
      ...(await fakeClient().getScenarioRelease(releaseId)),
      status: "rolled_back" as const,
      rollback_of_release_id: releaseId,
    }),
    archiveScenario: async () => ({ archived: true }),
    createPromotionRequest: async (_scenarioId, version) => ({ request_id: "req-fake", version, status: "pending" }),
    listPromotionRequests: empty,
    decidePromotionRequest: async () => ({ status: "approved" }),
    listConcurrencyPolicies: empty,
    registerCredentialBinding: async (body) => ({
      credential_ref: body.credential_ref,
      site_profile_id: body.site_profile_id,
      max_concurrency: body.max_concurrency,
      status: "active",
    }),
    rotateCredentialBinding: async (body) => ({
      credential_ref: body.credential_ref,
      site_profile_id: body.site_profile_id,
      status: "deprecated",
      replaced_by_credential_ref: body.new_credential_ref,
      replacement: {
        credential_ref: body.new_credential_ref,
        site_profile_id: body.site_profile_id,
        max_concurrency: body.max_concurrency ?? 1,
        status: "active",
      },
    }),
    decommissionCredentialBinding: async (body) => ({
      credential_ref: body.credential_ref,
      site_profile_id: body.site_profile_id,
      status: "revoked",
    }),
    deleteCredentialBinding: async () => ({ deleted: true }),
    listWorkerPools: async () => ({ items: [], assigned_pool_key: null, pending: { queued_runs: 0, oldest_queued_at: null } }),
    createWorkerPool: async (body) => ({
      pool_key: body.pool_key,
      description: body.description ?? null,
      status: "active",
      max_concurrency: body.max_concurrency ?? 1,
      priority: body.priority ?? "medium",
    }),
    updateWorkerPool: async (poolKey, body) => ({
      pool_key: poolKey,
      description: body.description ?? null,
      status: body.status ?? "active",
      max_concurrency: body.max_concurrency ?? 1,
      priority: body.priority ?? "medium",
    }),
    deleteWorkerPool: async (poolKey) => ({ pool_key: poolKey, deleted: true }),
    assignWorkerToPool: async (poolKey, workerId) => ({ pool_key: poolKey, worker_id: workerId }),
    removeWorkerFromPool: async (poolKey, workerId) => ({ pool_key: poolKey, worker_id: workerId, deleted: true }),
    assignWorkerPool: async (poolKey) => ({ assigned_pool_key: poolKey }),
    unassignWorkerPool: async () => ({ assigned_pool_key: null }),
    listScenarioVersions: async () => ({ items: [], next_cursor: null }),
    rollbackScenario: async (_scenarioId, _sourceVersion, latestVersion) => ({
      scenario_id: "00000000-0000-0000-0000-0000000000c1",
      version: latestVersion + 1,
      promotion_status: "draft",
    }),
    getRun: async (id) => ({ run_id: id, status: "running", worker_id: null, attempts: 1, as_of: null, failure_reason: null }),
    getRunSummary: async () => ({ by_status: {}, success_rate: null, total: 0, cache: { by_mode: {}, hit_rate: null } }),
    getRunTrends: async () => ({ window_days: 30, timezone: "Asia/Seoul", points: [] }),
    getWorkitem: async (id) => ({ workitem_id: id, status: "processing", unique_reference: "wi", attempts: 2, checked_out_by: "w-00000001", checked_out_at: "2026-06-15T00:00:00.000Z", run_id: "11111111-aaaa-bbbb-cccc-000000000001" }),
    getHumanTask: async (id) => ({ human_task_id: id, state: "open", kind: "approval", assignee: null, timeout: null, on_timeout: "escalate", run_id: null }),
    getScenario: async (id) => ({ scenario_id: id, name: "s", version: 1, promotion_status: "draft" }),
    getSite: async (id) => ({ site_profile_id: id, risk: "green", approval_status: "pending", circuit_status: "closed" }),
    getArtifact: async (id) => ({ artifact_id: id, type: "screenshot", sha256: "abc123", redaction_status: "redacted", retention_until: null, content: "redacted artifact content" }),
    getArtifactBlob: async () => new Blob(["redacted artifact content"], { type: "text/plain" }),
    getScenarioGenerationArtifact: async (generationId, artifactId) => ({
      artifact_id: artifactId,
      generation_id: generationId,
      type: "scenario_generation_llm_output",
      sha256: "abc123",
      redaction_status: "redacted",
      retention_until: null,
      content: "redacted generation artifact content",
    }),
    approveSite: async () => ({ site_profile_id: "s", approval_status: "approved" }),
    createSite: async () => ({
      site_profile_id: "s",
      name: "n",
      url_pattern: "https://x.example",
      risk: "green",
      approved: false,
      default_browser_identity_id: "browser-s",
      default_network_policy_id: "network-s",
    }),
    updateSite: async (siteId: string, name: string) => ({ site_profile_id: siteId, name }),
    updateSitePageState: async (siteId: string, pageStateSelectors: unknown | null) => ({
      site_profile_id: siteId,
      page_state_selectors: pageStateSelectors,
      page_state_summary: {
        configured: pageStateSelectors !== null,
        login_url_configured: false,
        authenticated_selector_configured: false,
        flag_count: 0,
        flags: [],
      },
    }),
    createPrincipal: async (body: { sub: string; display_name: string; email?: string | null }) => ({
      principal_id: "p",
      sub: body.sub,
      display_name: body.display_name,
      email: body.email ?? null,
      source: "manual" as const,
      external_id: null,
      idp_provider: null,
      lifecycle_source: "local" as const,
    }),
    updatePrincipal: async (principalId: string, body: { display_name?: string; email?: string | null }) => ({
      principal_id: principalId,
      sub: "s",
      display_name: body.display_name ?? "n",
      email: body.email ?? null,
      source: "manual" as const,
      external_id: null,
      idp_provider: null,
      lifecycle_source: "local" as const,
    }),
    deletePrincipal: async (principalId: string) => ({ principal_id: principalId, deleted: true }),
    listPrincipalRoleAssignments: async () => ({ items: [], next_cursor: null }),
    listRoleAssignments: async () => ({
      items: [
        {
          assignment_id: "67000000-0000-4000-8000-000000000001",
          principal_sub: "operator-a",
          role: "operator" as const,
          source: "manual" as const,
          external_id: null,
          idp_provider: null,
          lifecycle_source: "local" as const,
          status: "active" as const,
          reason: "initial console fixture",
          expires_at: null,
          granted_by: "admin-a",
          granted_at: "2026-06-24T00:00:00.000Z",
          revoked_by: null,
          revoked_at: null,
          revoke_reason: null,
          created_at: "2026-06-24T00:00:00.000Z",
          updated_at: "2026-06-24T00:00:00.000Z",
        },
      ],
      next_cursor: null,
    }),
    grantPrincipalRole: async (_principalId, body) => ({
      assignment_id: "67000000-0000-4000-8000-000000000099",
      principal_sub: "operator-a",
      role: body.role as "viewer" | "operator" | "reviewer" | "approver" | "admin",
      source: "manual" as const,
      external_id: null,
      idp_provider: null,
      lifecycle_source: "local" as const,
      status: "active" as const,
      reason: body.reason ?? null,
      expires_at: body.expires_at ?? null,
      granted_by: "admin-a",
      granted_at: "2026-06-24T00:10:00.000Z",
      revoked_by: null,
      revoked_at: null,
      revoke_reason: null,
      created_at: "2026-06-24T00:10:00.000Z",
      updated_at: "2026-06-24T00:10:00.000Z",
    }),
    revokeRoleAssignment: async (assignmentId, reason) => ({
      assignment_id: assignmentId,
      principal_sub: "operator-a",
      role: "operator" as const,
      source: "manual" as const,
      external_id: null,
      idp_provider: null,
      lifecycle_source: "local" as const,
      status: "revoked" as const,
      reason: "initial console fixture",
      expires_at: null,
      granted_by: "admin-a",
      granted_at: "2026-06-24T00:00:00.000Z",
      revoked_by: "admin-a",
      revoked_at: "2026-06-24T00:20:00.000Z",
      revoke_reason: reason,
      created_at: "2026-06-24T00:00:00.000Z",
      updated_at: "2026-06-24T00:20:00.000Z",
    }),
    captureSession: async (_siteId: string, _key: string) => ({ capture_session_id: "c", site_profile_id: "s", status: "launching" }),
    validateScenario: async () => ({ valid: true, report: { errors: [], warnings: [] } }),
    createScenario: async () => ({ scenario_id: "00000000-0000-0000-0000-0000000000c1", version: 1, promotion_status: "draft" }),
    updateScenario: async (_id, _ir, version) => ({ scenario_id: "00000000-0000-0000-0000-0000000000c1", version: version + 1, promotion_status: "draft" }),
    getScenarioGenerationCapabilities: async () => ({
      planner: { default_planner: "deterministic_mvp", available: ["deterministic_mvp", "llm_v1"] },
      visual_evidence: {
        screenshot: { enabled: true, policies: ["never", "failure", "each_step"], default_policy: "each_step" },
        video: { enabled: false, policies: ["never"], default_policy: "never", artifact_type: "video_masked", media_type: "video/webm" },
      },
    }),
    generateScenario: async (body) => ({
      generation_id: "00000000-0000-0000-0000-0000000000a1",
      mode: body.mode ?? "save_and_run",
      status: body.mode === "draft_only" ? "drafted" : "saved",
      prompt_hash: "hash",
      planner: body.planner ?? "deterministic_mvp",
      model: body.model ?? null,
      scenario_id: "00000000-0000-0000-0000-0000000000c1",
      scenario_version_id: "00000000-0000-0000-0000-0000000000c2",
      run_id: null,
      evidence_policy: body.evidence ?? { screenshot: "failure", video: "never" },
      blockers: [],
      created_at: "2026-06-15T00:00:00.000Z",
      created_by: "operator",
      draft_ir: { meta: { name: body.name ?? "prompt-hash" } },
      validation_report: { errors: [], warnings: [] },
    }),
    runScenarioGeneration: async (generationId, body) => ({
      generation_id: generationId,
      mode: "save_and_run",
      status: "run_queued",
      prompt_hash: "hash",
      planner: "deterministic_mvp",
      model: body.model ?? null,
      scenario_id: "00000000-0000-0000-0000-0000000000c1",
      scenario_version_id: "00000000-0000-0000-0000-0000000000c2",
      run_id: "00000000-0000-0000-0000-000000000099",
      evidence_policy: body.evidence ?? { screenshot: "failure", video: "never" },
      blockers: [],
      created_at: "2026-06-15T00:00:00.000Z",
      created_by: "operator",
      draft_ir: {},
      validation_report: {},
    }),
    listScenarioGenerations: async () => ({
      items: [
        {
          generation_id: "00000000-0000-0000-0000-0000000000a1",
          mode: "save_and_run",
          status: "run_queued",
          prompt_hash: "hash",
          planner: "deterministic_mvp",
          model: "gpt-4o-mini",
          scenario_id: "00000000-0000-0000-0000-0000000000c1",
          scenario_version_id: "00000000-0000-0000-0000-0000000000c2",
          run_id: "00000000-0000-0000-0000-000000000099",
          evidence_policy: { screenshot: "each_step", video: "never" },
          blockers: [],
          created_at: "2026-06-15T00:00:00.000Z",
          created_by: "operator",
          draft_ir: {},
          validation_report: {},
        },
      ],
      next_cursor: null,
    }),
    getScenarioGeneration: async (generationId) => ({
      generation_id: generationId,
      mode: "save",
      status: "saved",
      prompt_hash: "hash",
      planner: "deterministic_mvp",
      model: "gpt-4o-mini",
      scenario_id: "00000000-0000-0000-0000-0000000000c1",
      scenario_version_id: "00000000-0000-0000-0000-0000000000c2",
      run_id: null,
      evidence_policy: { screenshot: "each_step", video: "never" },
      blockers: [],
      created_at: "2026-06-15T00:00:00.000Z",
      created_by: "operator",
      draft_ir: {},
      validation_report: {},
    }),
    createRun: async () => ({ run_id: "00000000-0000-0000-0000-000000000099", status: "queued" }),
    pauseRun: async () => ({ status: "accepted" }),
    decideApproval: async (body) => ({
      decision_id: "00000000-0000-0000-0000-0000000000de",
      source_run_id: body.source_run_id,
      doc_ref: body.doc_ref,
      decision: body.decision,
      spawned_run_id: "00000000-0000-0000-0000-0000000000d9",
    }),
    ...overrides,
  };
}
